<?

	if($_GET['nome'] == 'recibo_provisorio'){
		$mysql->prepare = array($_GET['id']);
		$mysql->filtro = " WHERE id = ? AND situacao = 2 ";
		$lotes = $mysql->read_unico('lotes');

	} elseif($_GET['nome'] == 'termo_arrematacao'){
		$mysql->prepare = array($_GET['id']);
		$mysql->filtro = " WHERE id = ? AND situacao = 2 ";
		$lotes = $mysql->read_unico('lotes');

	} elseif($_GET['nome'] == 'nota1'){
		$url = DIR_C.DIR_D;
		$url = isset($_GET['emitir_nota_txt']) ? str_replace($_GET['emitir_nota_txt'], base64_encode($_GET['emitir_nota_txt']), $url) : '';
		$url = str_replace('/imprimir/nota1/?', '/imprimir/nota/?', $url);
		location($url);

	} elseif($_GET['nome'] == 'nota'){
		$ids = array(0);
		$ex = explode('-', $_GET['ids']);
		foreach ($ex as $key => $value) {
			if($value){
				$ids[] = $value;
			}
		}
		$mysql->filtro = " WHERE id IN (".implode(',', $ids).")  AND situacao = 2 ";
		$lotes = $mysql->read('lotes');

	} elseif($_GET['nome'] == 'etiqueta'){
		$ids = array(0);
		$ex = explode('-', $_GET['ids']);
		foreach ($ex as $key => $value) {
			if($value){
				$ids[] = $value;
			}
		}
		$mysql->filtro = " WHERE id IN (".implode(',', $ids).") ";
		$lotes = $mysql->read('lotes');
	}

	$mysql->filtro = " WHERE `tipo` = 'info_termos_e_notas' ";
	$info_termos_e_notas = $mysql->read_unico('configs');


	//leiloes








	if(isset($lotes->id) OR isset($lotes[0]->id)){

		$lote = isset($lotes->id) ? $lotes : $lotes[0];

		$mysql->prepare = array($lote->lances_cadastro);
		$mysql->filtro = " WHERE id = ? ";
		$cadastro = $mysql->read_unico('cadastro');

		if( isset($_SESSION['x_admin']->id) OR (isset($_SESSION['x_site']->id) AND $_SESSION['x_site']->id==$cadastro->id) ){

            $mysql->prepare = array($lote->leiloes);
            $mysql->filtro = " WHERE id = ? ";
            $leiloes = $mysql->read_unico('leiloes');

            ?>

			<div style="<?=$_GET['nome']=='etiqueta' ? 'width: 600px; border: 0;' : 'width: 800px; border: 2px solid #666;' ?> padding: 1px; margin: 20px auto; font-size: 12px; font-family: Arial, Helvetica, sans-serif;">

				<? if($_GET['nome'] != 'etiqueta'){ ?>
					<table cellpadding="0" cellspacing="0" border="1" style="width:100%">
						<tr>
							<td style="text-align: center; border-right: 0">
								<div style="padding-top: 10px"><img src="<?=DIR_C?>/web/img/z_leilao/logo.png" style="max-width:200px;"></div>
							</td>
							<td rowspan="2" style="text-align: center; border-left: 0; border-right: 0">
				                <div style="font-size:20px; font-weight:bold"><?=$info_termos_e_notas->nome?></div>
				                <div style="font-size:12px; font-weight:bold"><?=$info_termos_e_notas->tipo1?></div>
				                <div style="font-size:11px"><?=$info_termos_e_notas->empresa?></div>
				                <div style="font-size:11px"><div style="width: 200px; display: inline-block;"><?=$info_termos_e_notas->endereco?></div></div>
				                <div style="font-size:11px">Telefone <?=$info_termos_e_notas->telefone?></div>
				                <div style="font-size:11px; font-weight:bold"><?=DIR_C?></div>
				            </td>
							<td rowspan="2" style="text-align: center; border-left: 0">
								<div style="font-size:24px; font-weight:bold">
									<? if($_GET['nome'] == 'recibo_provisorio'){ ?>
										<div style="padding: 5px 0;">
											TERMO<br> PROVISÓRIO<br> DE ARREMATAÇÃO
										</div>
										<div style="padding-bottom: 5px; font-size: 16px"><b>EMISSÃO: <?=data($lote->lances_data)?></b></div>
									<? } elseif($_GET['nome'] == 'termo_arrematacao'){ ?>
										<div style="padding: 20px 0 12px;">
											TERMO DE<br> ARREMATAÇÃO
										</div>
										<div style="padding-bottom: 8px; font-size: 16px"><b>EMISSÃO: <?=$lote->emissao ? $lote->emissao : data($lote->lances_data)?></b></div>
									<? } elseif($_GET['nome'] == 'nota'){ ?>
										<div style="padding: 20px 0 12px;">
											NOTA DE<br> VENDA <br>
										</div>
										<div style="padding-bottom: 8px; font-size: 16px"><b>EMISSÃO: <?=$lote->emissao ? $lote->emissao : data($lote->lances_data)?></b></div>
									<? } ?>
								</div>
							</td>
						</tr>
				    </table>
			    <? } ?>















				<? if($_GET['nome'] == 'recibo_provisorio'){ ?>
					<div style="height: 20px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td><b>Leilão:</b> <?=$leiloes->nome?></td>
                            <td><b>Lote:</b> <?=$lote->nome?></td>
							<td colspan="2"><b>Data do leilão:</b> <?=data($lote->data)?></td>
						</tr>
						<tr>
							<td colspan="2"><b>Arrematante:</b> <?=$cadastro->nome?></td>
                                                        <td colspan="2"><b>Arrematante:</b> <?=$cadastro->email?></td>
							<td colspan="2"><b>CPF/CNPJ:</b> <?=$cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf?></td>
						</tr>
						<tr>
							<td colspan="2"><b>Rua/Av:</b> <?=$cadastro->rua?></td>
							<td><b>Nº:</b> <?=$cadastro->numero?></td>
							<td><b>Compl.:</b> <?=$cadastro->complemento?></td>
						</tr>
						<tr>
							<td><b>Bairro:</b> <?=$cadastro->bairro?></td>
							<td><b>CEP:</b> <?=$cadastro->cep?></td>
							<td colspan="2"><b>Cidade:</b> <?=$cadastro->cidades?> / <?=$cadastro->estados?></td>
						</tr>
						<tr>
							<td colspan="2"><b>Telefones:</b> <?=$cadastro->telefone?> <?=$cadastro->celular?></td>
                                                        <td><b>RG:</b> <?=$cadastro->rg?></td>
						</tr>
					</table>

					<div style="height: 20px"></div>
					<? $lances = array('lance'=>0, 'comissao'=>0, 'despesas'=>0); ?>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td colspan="6" align="center"><b>RELAÇÃO DE LOTES</b></td>
						</tr>
						<tr>
							<td><b>LOTE</b></td>
							<td><b>VL. ARREMATADO</b></td>
							<td><b>COMISSÃO</b></td>
							<td><b>OUTRAS DESPESAS</b></td>
							<!--<td><b>TOTAL</b></td>-->
							<td><b>SITUAÇÃO</b></td>
						</tr>
						<!-- Nao tem foreach pq eh so 1, mais ja ta ponto para o oreach -->
						<?
							$comissao_porc = $info_termos_e_notas->valor;
							if($lote->comissao){
								$comissao_porc = $lote->comissao;
							}
							$comissao_valor = $lote->lances*$comissao_porc/100;
						?>
							<tr>
								<td><?=(int)$lote->ordem?></td>
								<td>
									<?=preco($lote->lances, 1)?>
									<? $lances['lance'] += $lote->lances ?>
								</td>
								<td>
									<?=preco( ($comissao_valor) , 1)?>
									<? $lances['comissao'] += $comissao_valor ?>					
								</td>
								<td>
									<?=preco($lote->outras_despesas, 1)?>
									<? $lances['despesas'] += $lote->outras_despesas ?>
								</td>
								<td><?=preco( $lote->lances+$comissao_valor+$lote->outras_despesas, 1)?></td>
								<td>Arrematado</td>
							</tr>
						<tr>
							<td><b>TOTAL</b></td>
							<td><b><?=preco($lances['lance'], 1)?></b></td>
							<td><b><?=preco($lances['comissao'], 1)?></b></td>
							<td><b><?=preco(0, 1)?></b></td>
							<!--<td>
								<b>
									<? $total = $lances['lance']+$lances['comissao']+$lances['despesas']?>
									<?=preco($total, 1)?>
								</b>
							</td>-->
							<td><b></b></td>
						</tr>
					</table>

					<div style="padding: 10px;">
						<div style="padding-top: 0px"><b>VALOR TOTAL DOS ARREMATADOS:</b> <?=preco($total, 1)?></div>
						<!--<div style="padding-top: 2px"><b>VALOR TOTAL DOS CONDICIONAIS:</b> <?=preco(0, 1)?></div>-->
						<!--<div style="padding-top: 2px"><b>TOTAL GERAL:</b> <?=preco($total, 1)?></div>-->
					</div>

					<!--<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td colspan="6" align="center"><b>PAGAMENTOS EFETUADOS</b></td>
						</tr>
						<tr>
							<td><b>VALOR</b></td>
							<td><b>REFERENTE</b></td>
							<td><b>FORMA PAGAMENTO</b></td>
						</tr>
						<tr>
							<td><?=preco($lances['lance'], 1)?></td>
							<td>Arrematação</td>
							<td>Depósito bancário</td>
						</tr>
						<tr>
							<td><?=preco($lances['comissao'], 1)?></td>
							<td>Comissão</td>
							<td>Depósito bancário</td>
						</tr>
					</table>-->
					
					<div style="padding: 5px 10px 0; margin-top: 20px; font-size: 14px; border: 2px solid #666;">
                                            <br/><br/>
                                            
						<div style="font-size: 22px; text-align: center;"><b>FORMA DE PAGAMENTO</b></div>
                                                <div style="padding-top: 15px"><b>O pagamento dever&aacute; ser feito atrav&eacute;s de dep&oacute;sito, transfer&ecirc;ncia ou TED, para a conta da leiloeira em at&eacute; 1 dia &uacute;til</b> </div>
                                                <br/>
                                                <div style="padding-top: 15px; font-size: 20px; text-align: center;"><b>Dados para Dep&oacute;sito</b> </br>BANCO BRADESCO - 237 </br>AG: 0849 </br>CONTA CORRENTE: 21400-0 </br>VIVIANE GARZON CORREA </br>CPF: 002.330.006-07
</div>                                          <br/><br/>
						<!--<div style="padding-top: 15px"><b>Valor Total da ARREMATAÇÃO dos lotes vendidos:</b> <?=preco($lances['lance'], 1)?></div>
						<div style="padding-top: 2px"><b>Valor Total da COMISSÂO dos lotes vendidos:</b> <?=preco($lances['comissao'] , 1)?></div>
						<div style="padding-top: 2px"><b>Valor Total da DESPESAS dos lotes vendidos:</b> <?=preco($lances['despesas'] , 1)?></div>-->
						<div style="padding-top: 15px; font-size: 18px"><b>VALOR TOTAL DO DEPÓSITO: <?=preco($total , 1)?></b></div>
						<!--<<div style="padding-top: 2px; padding-bottom: 10px; font-size: 18px"><b>DATA LIMITE PARA DEPÓSITO: <?=$lote->dias_uteis?> &aacute;Uteis Ap&acute;os Arremata&ccedil;&atilde;o</b></div>-->
                                                <div style="padding-top: 2px; padding-bottom: 10px; font-size: 18px"><b>RETIRADA: A retirada dos lotes dever&aacute; ser feita em at&eacute; 3 dias &uacute;teis após arremata&ccedil;&atilde;o</b></div>
                                                <div style="font-size: 20px;"><b>Em caso de desist&ecirc;ncia, dever&aacute; ser pago o valor referente a 20% do Lance.</b> </div>
					</div>

					<div style="padding: 35px 0 15px; font-size: 12px; text-align: center;">
						__________________________________________________________________________
						<div>ASSINATURA</div>
					</div>

















				<? } elseif($_GET['nome'] == 'termo_arrematacao'){ ?>
					<div style="height: 20px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<? $comitentes = rel('leiloes', $lote->leiloes, 'comitentes') ?>
							<td colspan="2"><b>COMITENTE:</b> <?=comitentes($comitentes)?></td>
							<td colspan="2"><b>CPF/CNPJ:</b> <?=comitentes($comitentes, 'cpf_cnpj')?></td>
						</tr>
						<tr>
							<td colspan="2"><b>DATA DO LEILÃO:</b> <?=data( rel('leiloes', $lote->leiloes, 'data') , 'd/m/Y H:i:s')?></td>
							<td colspan="2"><b>Nº LEILÃO:</b> <?=rel('leiloes', $lote->leiloes, 'codigo')?></td>
						</tr>
					</table>

					<div style="padding: 20px 10px 0">
						<b style="font-size: 24px">LOTE - <?=(int)$lote->ordem?></b>
						<div style="padding-top: 5px"><?=txt($lotes)?></div>
					</div>

					<div style="height: 20px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td colspan="3" style="font-size: 22px"><b>VALOR DA ARREMATAÇÃO: <?=preco($lote->lances, 1)?></b></td>
							<td style="font-size: 22px; text-align: center;"><b>Vendido</b></td>
						</tr>
						<tr>
							<td colspan="4"><b>Arrematante:</b> <?=$cadastro->nome?></td>
						</tr>
						<tr>
							<td><b>CPF/CNPJ:</b> <?=$cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf?></td>
							<td><b>Telefones:</b> <?=$cadastro->telefone?></td>
							<td colspan="2"><b>Celular:</b> <?=$cadastro->celular?></td>
						</tr>
						<tr>
							<td colspan="2"><b>Rua/Av:</b> <?=$cadastro->rua?></td>
							<td><b>Nº:</b> <?=$cadastro->numero?></td>
							<td><b>Compl.:</b> <?=$cadastro->complemento?></td>
						</tr>
						<tr>
							<td><b>Bairro:</b> <?=$cadastro->bairro?></td>
							<td><b>CEP:</b> <?=$cadastro->cep?></td>
							<td colspan="2"><b>Cidade:</b> <?=$cadastro->cidades?> / <?=$cadastro->estados?></td>
						</tr>
					</table>

					<div style="padding-top: 20px; text-align: center;">
						<b style="font-size: 22px">FORMA DE PAGAMENTO</b>
						<div style="font-size: 11px"><b>PAGAMENTOS DE ARREMATAÇÃO + COMISSÃO + TAXAS + DESPESAS</b></div>
					</div>

					<div style="padding: 20px 10px 0; font-size: 14px">
						<div style="padding-top: 0px"><b>Valor da Arrematação:</b> <?=preco($lote->lances, 1)?></div>
						<div style="padding-top: 2px"><b>Valor da Comissão do leiloeiro:</b> <?=preco( ($lote->lances*5/100) , 1)?></div>
						<div style="padding-top: 2px"><b>Valor da Taxa:</b> <?=preco(0, 1)?></div>
						<div style="padding-top: 2px"><b>Valor das Despesas:</b> <?=$lote->outras_despesas?></div>
					
					
						<div style="padding-top: 2px; font-size: 20px"><b>Valor Total do Depósito: <?=preco($lote->outras_despesas+$lote->lances+($lote->lances*5/100) , 1)?></b></div>
					
                                        
                                        </div>

					<div style="height: 20px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td align="center" style="padding-top: 20px">
								____________________________________________
								<div>ASSINATURA DO ARREMATANTE</div>
							</td>
							<td align="center">
								<b>Confirmo o lance acima e declaro estar ciente<br> e de acordo  com todas as condições<br> estabelecidas no catálogo e edital de leilão.</b>
							</td>
						</tr>
					</table>
















				<? } elseif($_GET['nome'] == 'nota'){ ?>
					<div style="height: 1px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<? $comitentes = rel('leiloes', $lote->leiloes, 'comitentes') ?>
							<td colspan="2"><b>COMITENTE:</b> <?=comitentes($comitentes)?></td>
							<td colspan="2"><b>CPF/CNPJ:</b> <?=comitentes($comitentes, 'cpf_cnpj')?></td>
						</tr>
						<tr>
							<td colspan="2"><b>DATA DO LEILÃO:</b> <?=data( rel('leiloes', $lote->leiloes, 'data') , 'd/m/Y H:i:s')?></td>
							<td colspan="2"><b>Nº LEILÃO:</b> <?=rel('leiloes', $lote->leiloes, 'codigo')?></td>
						</tr>
						<tr>
							<td colspan="4"><b>Nome:</b> <?=$cadastro->nome?></td>
						</tr>
						<tr>
							<td><b>CPF/CNPJ:</b> <?=$cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf?></td>
							<td><b>Telefones:</b> <?=$cadastro->telefone?></td>
							<td colspan="2"><b>Celular:</b> <?=$cadastro->celular?></td>
						</tr>
						<tr>
							<td colspan="2"><b>Rua/Av:</b> <?=$cadastro->rua?></td>
							<td><b>Nº:</b> <?=$cadastro->numero?></td>
							<td><b>Compl.:</b> <?=$cadastro->complemento?></td>
						</tr>
						<tr>
							<td><b>Bairro:</b> <?=$cadastro->bairro?></td>
							<td><b>CEP:</b> <?=$cadastro->cep?></td>
							<td colspan="2"><b>Cidade:</b> <?=$cadastro->cidades?> / <?=$cadastro->estados?></td>
						</tr>
					</table>

					<? $lance = 0; ?>
					<div style="height: 1px"></div>
					<table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
						<tr>
							<td align="center" style="background: #f4f4f4"><b>LOTE</b></td>
							<td style="background: #f4f4f4"><b></b></td>
							<td align="center" style="background: #f4f4f4"><b>VALOR</b></td>
						</tr>
						<tr>
							<td colspan="3" style="padding: 0; border-top: 0"></td>
						</tr>
						<?
							for ($i=1; $i <= 10; $i++) {
								if(count($lotes) < $i){
									$lotes[] = (object)array('ordem'=>'', 'nome'=>'&nbsp;', 'lances'=>0);
								}
							}
						?>
						<? foreach ($lotes as $key => $value) { ?>
							<tr>
								<td align="center" style="width: 15%; border-top: 0; border-bottom: 0">
									<div style="padding-bottom: 5px"><?=$value->ordem ? (int)$value->ordem : ''?></div>
								</td>
								<td style="border-top: 0; border-bottom: 0">
									<div style="padding-bottom: 5px"><?=$value->nome?></div>
								</td>
								<td align="center" style="width: 30%; border-top: 0; border-bottom: 0">
									<div style="padding-bottom: 5px">
										<?=$value->lances ? preco($value->lances, 1) : ''?>
										<? $lance += $value->lances ?>
									</div>
								</td>
							</tr>
						<? } ?>
						<tr>
							<td colspan="3" style="padding: 0; border-top: 0"></td>
						</tr>
						<tr>
							<td colspan="2" style="vertical-align: top;">
								<?
									$mysql->filtro = " WHERE  `tipo` = 'informacoes' AND lang = '".LANG."' ";
									$info = $mysql->read_unico('configs');
								?>
								<table cellpadding="0" cellspacing="0" border="0" style="width:100%;">
									<tr>
										<td style="width: 40px; vertical-align: top;">OBS.:</td>
										<td><?=isset($_GET['emitir_nota_txt']) ? $_GET['emitir_nota_txt'] : ''?></td>
									</tr>
								</table>
							</td>
							<td>
								<table cellpadding="0" cellspacing="0" border="0" style="width:100%;">
									<tr>
										<td style="width: 100px"><b>SUB TOTAL</b></td>
										<td><?=preco($lance, 1)?></td>
									</tr>
									<tr>
										<td style="width: 100px; padding-top: 5px"><b>COMISSÃO</b></td>
										<td><?=preco( ($lance*5/100) , 1)?></td>
									</tr>
									<tr style="font-size: 16px">
										<td style="width: 100px; padding-top: 5px"><b>TOTAL</b></td>
										<td><b><?=preco( $lance+($lance*5/100) , 1)?></b></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>









				<? } elseif($_GET['nome'] == 'etiqueta'){ ?>
					<? foreach ($lotes as $key => $value) { ?>
						<table cellpadding="0" cellspacing="0" border="1" style="width:100%; height: 500px;">
							<tr  style="height: 120px;">
								<td style="text-align: center; border-right: 0">
									<div style="padding-top: 10px"><img src="<?=DIR_C?>/web/img/z_leilao/logo.png" style="max-width:200px;"></div>
								</td>
								<td style="text-align: center; border-left: 0">
					                <div style="font-size:40px; font-weight:bold">LOTE: <?=(int)$value->ordem?></div>
					                <div style="font-size:24px; font-weight:bold">LEILÃO: <?=rel('leiloes', $value->leiloes, 'codigo')?></div>
					            </td>
							</tr>
							<tr>
								<td colspan="2" style="padding: 10px; text-align: justify; vertical-align: top">
									<b style="font-size: 16px">Descrição do lote:</b>
									<div style="padding: 5px; padding-bottom: 0px; font-size: 14px"><?=txt($value)?></div>
								</td>
							</tr>
							<tr style="height: 80px;">
								<td style="padding: 5px; font-size: 16px; text-align: center; border-right: 0">
									<b>Data do leilão:</b> <?=data($value->data_ini, 'd/m/Y H:i')?>
								</td>
								<td style="padding: 5px; font-size: 16px; text-align: center; border-left: 0">
									<b>Lance inicial:</b> <?=preco($value->lance_ini, 1)?>
								</td>
							</tr>
							<tr style="height: 80px;">
								<td colspan="2" style="padding: 5px; font-size: 16px; text-align: center;">
									<b><?=DIR_C?> | &#9742; <?=$info_termos_e_notas->telefone?></b>
								</td>
							</tr>
					    </table>
					    <div style="height: 20px"></div>
					<? } ?>


				<? } ?>












			</div>

		<? } else { ?>
			<? $ids = isset($_GET['ids']) ? '?ids='.$_GET['ids'] : '' ?>
			<? location(DIR.'/login/'.$_GET['pg'].'/'.$_GET['nome'].'/'.$_GET['id'].'/'.$ids); ?>
		<? } ?>

	<? } else { ?>
		Ação Não Permitida!<br>
		Esse Lote Não Foi Arrematado ou Não Foi Pago!
	<? } ?>
