
	<? if($_GET['nome'] == '-') $_GET['nome'] = 'dados'; ?>

	<section id="minha_conta" class="centerr">


		<div class="centerr pt40 pb40">
			<div class="fz30 fwb texto_laranja"><?=lang('Minha Conta')?></div>
			<div class="h50"></div>
		
			<div class="wr2">
				<ul class="pb20">
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='dados' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/dados/"><?=lang('Meu Cadastro')?></a></li>
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='documentos' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/documentos/"><?=lang('Meus Documentos')?></a></li>
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='meus_leiloes' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/meus_leiloes/"><?=lang('Leilões que Participo')?></a></li>
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='habilitacoes' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/habilitacoes/"><?=lang('Minhas Habilitações')?></a></li>
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='lotes_arrematados' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/lotes_arrematados/"><?=lang('Meus Lotes Arrematados')?></a></li>
					<li class="p10 pl20 pr20 mb10 back_F1F1F1 <?=$_GET['nome']=='meus_lances' ? 'fwb' : ''?>"><a href="<?=DIR?>/minha_conta/meus_lances/"><?=lang('Meus Lances')?></a></li>
					<li class="p10 pl20 pr20 mb10"><a onclick="ajaxNormal('ajaxForm/login.php?sair=1');"><?=lang('Sair')?></a></li>
				</ul>
			</div>





			<div class="wr10 pl20 p0_700">
				<div <? if($_GET['nome'] != 'meus_leiloes') { ?> class="borda_arredondada borda_leiloes" <? } ?> >



					<? if($_GET['nome'] == 'dados'){ ?>
                        <div class="p20 fz26 fwb texto_roxo borda_laranja_bottom"><?=lang('Dados Cadastrais')?></div>
						<div class="wr6 pb20 pl20 pt20">

							<div class="fz16">
								<div class="mr20"> <b class="w60 pb10 dib"><?=lang('Status')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->status ? lang('Habilitado para participar dos Leilões') : lang('Aguardando validação de cadastro')?></span> </div>
								<div class="mr20"> <b class="w60 pb10 dib"><?=lang('Nome')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->nome?> <?=$cadastro_pd->sobrenome?> <?=isset($cadastro_pd->sobrenome) ? $cadastro_pd->sobrenome : '';?></span> </div>
								<div class="mr20"> <b class="w60 pb10 dib"><?=lang('Email')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->email?></span> </div>
								<div class="mr20"> <b class="w60 pb10 dib"><?=lang('Login')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->login?></span> </div>
								<? if($cadastro_pd->tipo == 1){ ?>
									<div class="mr20"> <b class="w60 pb10 dib"><?=lang('CNPJ')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->cnpj?></span> </div>
									<div class="mr20"> <b class="w60 pb10 dib"><?=lang('IE')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->ie?></span> </div>
								<? } else { ?>
									<div class="mr20"> <b class="w60 pb10 dib"><?=lang('CPF')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->cpf?></span> </div>
									<div class="mr20"> <b class="w60 pb10 dib"><?=lang('RG')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->rg?></span> </div>
								<? } ?>
								<div class="h20"></div>

							</div>
						</div>
						<div class="wr6">
							<div class="tac fz24 fwb pb30">&nbsp; </div>
							<div class="fz16">
								<? if($cadastro_pd->tipo == 0){ ?>
									<div class="mr20"> <b class="w80 pb10 dib"><?=lang('Nasc.')?>:</b> <span class="pb10 dib"><?=data($cadastro_pd->nascimento)?></span> </div>
									<div class="mr20"> <b class="w80 pb10 dib"><?=lang('Sexo')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->sexo==0 ? lang('Feminino') : lang('Masculino')?></span> </div>
								<? } ?>
								<div class="mr20"> <b class="w80 pb10 dib"><?=lang('Telefone')?>:</b> <span class="pb10 dib"><?=$cadastro_pd->telefone?></span> </div>
								<div class="mr20"> <b class="w80 pb10	 dib"><?=lang('Celular')?>:</b> <?=$cadastro_pd->celular?> </div>
								<div class="mr20"> <b class="w80 pb10 dib"><?=lang('Endereço')?>:</b> <?=$cadastro_pd->rua?>, <?=$cadastro_pd->numero?> <?=$cadastro_pd->complemento?>, <?=$cadastro_pd->bairro?>, <?=$cadastro_pd->cidades?>/<?=$cadastro_pd->estados?> </div>
							</div>
						</div>
						<div class="clear"></div>

                        <div class="p20 borda_laranja_top">
                            <a onclick="boxs('cadastro_editar', '', 1)" class="cor_337ab7 link texto_negrito"><?=lang('Editar Dados')?></a>
                            <? if($cadastro_pd->senha != 'facebook'){ ?>
                                &nbsp; | &nbsp;
                                <a onclick="boxs('cadastro_editar_senha')" class="cor_337ab7 link texto_negrito"><?=lang('Editar Senha')?></a>
                            <? } ?>
                        </div>




					<? } elseif($_GET['nome'] == 'documentos'){ ?>
						<?
							if(isset($_POST['cadastro_documentos_tipo'])){
								$table = 'cadastro_documentos';
								$mysql->campo['cadastro_documentos_tipo'] = $_POST['cadastro_documentos_tipo'];
								$mysql->campo['cadastro'] = $_SESSION['x_site']->id;
								$ult_id = $mysql->insert($table);
					            // Fotos
					            $upload = new Upload();
					            if(isset($_FILES)){
					            	$nome = $upload->fileUpload($ult_id, '../', 0, 'cadastro_documentos');
					            }

								$mysql->colunas = 'email';
								$mysql->filtro = " WHERE `lang` = '".LANG."' AND `tipo` = 'emails' ";
								$emails = $mysql->read_unico("configs");

								$email = new Email();
								$email->to = $emails->email;
								$email->assunto = 'Documentos Enviados no site '.nome_site();
								$email->txt = 'Um novo documento foi enviado pelo usuario '.$cadastro_pd->nome.'<br><br><a href="'.DIR_C.'/web/fotos/'.$nome[0].'">'.lang('Ver Documento').'</a>';
								$email->enviar();

								location(DIR.'/minha_conta/'.$_GET['nome'].'/');
							}
						?>
                        <div class="p20 fz26 fwb texto_roxo borda_laranja_bottom"><?=lang('Documentos')?></div>
						<div class="p20">

							<?
								$mysql->filtro = " WHERE ".STATUS." ";
								$cadastro_documentos_tipo = $mysql->read('cadastro_documentos_tipo');
							?>
							<div class="dib p20 pb0 mb20 enviar_documento">
								<form method="post" action="" enctype="multipart/form-data" >
									<div class="fll pt10 mb20 fwb"><?=lang('Enviar Documento')?>:</div>
									<div class="max-w200 fll pl10 mb20">
										<select name="cadastro_documentos_tipo" class="w100p h25 design">
											<? foreach ($cadastro_documentos_tipo as $key => $value) { ?>
												<option value="<?=$value->id?>"><?=$value->nome?></option>
											<? } ?>
										</select>
									</div>
									<div class="fll pt5 pl10 mb20"><input type="file" name="foto"></div>
									<div class="fll pl10 mb20"><button class="botao fundo_roxo texto_branco"><?=lang('Enviar')?></button></div>
									<div class="clear"></div>
								</form>
							</div>

							<div class="pt5 pb10 fwb"><?=lang('Tabela de Documentos')?>:</div>
							<table class="w100p">
								<tr>
									<th class="w150 tal table_top borda_laranja_bottom"><?=lang('Data')?></th>
									<th class="tal table_top borda_laranja_bottom"><?=lang('Tipo')?></th>
									<th class="tac table_top borda_laranja_bottom"><?=lang('Anexo')?></th>
								</tr>
								<?
									$mysql->filtro = " WHERE `cadastro` = '".$_SESSION['x_site']->id."' order by id desc ";
									$cadastro_documentos = $mysql->read('cadastro_documentos');
								?>
								<? foreach ($cadastro_documentos as $key => $value) { ?>
									<tr>
										<td class="tal table_center"><?=data($value->data, 'd/m/Y')?></td>
										<td class="tal table_center"><?=rel('cadastro_documentos_tipo', $value->cadastro_documentos_tipo)?></td>
										<td class="tac table_center"><a href="<?=DIR?>/web/fotos/<?=$value->foto?>" target="_blank" class="link cor_00f"><?=lang('Download')?></a></td>
									</tr>
								<? } ?>
								<? if(!$cadastro_documentos){ ?>
									<tr>
										<td class="tac table_center" colspan="3"><?=lang('Nenhum documento encontrado')?>...</td>
									</tr>
								<? } ?>
							</table>
						</div>





					<? } elseif($_GET['nome'] == 'habilitacoes'){ ?>
                        <div class="p20 fz26 fwb texto_roxo borda_laranja_bottom"><?=lang('Minhas Habilitações')?></div>
                        <div class="p20">

							<table class="w100p">
								<tr class="">
									<th class="w200 tal table_top borda_laranja_bottom"><?=lang('Data')?></th>
									<th class="tal table_top borda_laranja_bottom"><?=lang('Leilão')?></th>
								</tr>
								<?
									$mysql->prepare = array($_SESSION['x_site']->id);
									$mysql->filtro = " WHERE `cadastro` = ? ";
									$leiloes_habilitacoes = $mysql->read('leiloes_habilitacoes');
								?>
								<? foreach ($leiloes_habilitacoes as $key => $value) { ?>
									<tr>
										<td class="tal table_center"><?=data($value->data, 'd/m/Y H:i')?></td>
										<td class="tal table_center"><?=rel('leiloes', $value->leiloes)?></td>
									</tr>
								<? } ?>
							</table>
						</div>





					<? } elseif($_GET['nome'] == 'lotes_arrematados'){ ?>
                        <div class="p20 fz26 fwb texto_roxo borda_laranja_bottom"><?=lang('Meus Lotes Arrematados')?></div>
						<div class="p20">

							<table class="w100p">
								<tr>
									<th class="w200 tal table_top borda_laranja_bottom"><?=lang('Data')?></th>
									<th class="tac table_top borda_laranja_bottom"><?=lang('Leilão')?></th>
									<th class="tal table_top borda_laranja_bottom"><?=lang('Lance')?></th>
								</tr>
								<?
									$mysql->prepare = array($_SESSION['x_site']->id);
									$mysql->filtro = " WHERE `lances_cadastro` = ? AND lances > 0 AND situacao = 2 ";
									$lotes = $mysql->read('lotes');
								?>
								<? foreach ($lotes as $key => $value) { ?>
									<tr>
										<td class="tal table_center"><?=data($value->data, 'd/m/Y H:i')?></td>
										<td class="tal table_center"><?=$value->nome?></td>
										<td class="tal table_center"><?=preco($value->lances, 1)?></td>
									</tr>
								<? } ?>
							</table>
						</div>




					<? } elseif($_GET['nome'] == 'meus_lances'){ ?>
                        <div class="p20 fz26 fwb texto_roxo borda_laranja_bottom"><?=lang('Meus Lances')?></div>
						<div class="p20">
							<table class="w100p">
								<tr>
									<th class="w200 tal table_top borda_laranja_bottom"><?=lang('Data')?></th>
									<th class="tal table_top borda_laranja_bottom"><?=lang('Lote')?></th>
									<th class="tal table_top borda_laranja_bottom"><?=lang('Lance')?></th>
								</tr>
								<?
									$lances = array();
									$mysql->prepare = array($_SESSION['x_site']->id);
									$mysql->filtro = " WHERE `lances_cadastro` = ? AND lances > 0 ";
									$lotes = $mysql->read('lotes');
									foreach ($lotes as $key => $value) {
										$lances[$value->lances_data.'-l'.$key]['data'] = $value->lances_data;
										$lances[$value->lances_data.'-l'.$key]['nome'] = $value->nome;
										$lances[$value->lances_data.'-l'.$key]['lances'] = $value->lances;
									}

									$mysql->prepare = array($_SESSION['x_site']->id);
									$mysql->filtro = " WHERE `cadastro` = ? ";
									$lotes_lances = $mysql->read('lotes_lances');
									foreach ($lotes_lances as $key => $value) {
										$lances[$value->data.'-'.$key]['data'] = $value->data;
										$lances[$value->data.'-'.$key]['nome'] = rel('lotes', $value->lotes);
										$lances[$value->data.'-'.$key]['lances'] = $value->lances;
									}
									krsort($lances);
								?>
								<? foreach ($lances as $key => $value) { ?>
									<tr>
										<td class="tal table_center"><?=data($value['data'], 'd/m/Y H:i')?></td>
										<td class="tal table_center"><?=$value['nome']?></td>
										<td class="tal table_center"><?=preco($value['lances'], 1)?></td>
									</tr>
								<? } ?>
 							</table>
							<? if(!$lances){ ?>
								<div class="p20 tac bd_aaa bdt0 back_fff"><?=lang('Nenhum item encontrado')?>...</div>
							<? } ?>
						</div>



					<? } elseif($_GET['nome'] == 'meus_leiloes'){ ?>


                        <?
                        $mysql->filtro = "WHERE cadastro = '".$_SESSION['x_site']->id."'";
                        $habilitacao = $mysql->read('leiloes_habilitacoes');

                        echo '<ul class="pt20">';
                        foreach ($habilitacao as $valss){


                            $mysql->filtro = "WHERE id = '".$valss->lotes."' AND situacao = '0' AND status = '1'";
                            $value = $mysql->read_unico('lotes');

                            if(count($value) > 0):
                                 $tipo_box = tipo_box($value);

                            echo '<li class="wr5 pb20 borda_leiloes LL_box_'.$tipo_box.'">';
                            include 'z_leilao.phtml';

                            echo '</li>';
                            endif;
                        }
                        echo '<li class="clear"></li>';
                        echo '</ul>';

                        ?>

                    <? } ?>

                    <? // include 'z_leilao.phtml' ?>
				</div>
			</div>
			<div class="clear"></div>



		</div>



	</section>


    <? $leiloes = array_merge($leiloes, $leiloes_star) ?>
    <?=leiloes($leiloes, $lotes_star)?>