
	<section id="textos">

		<div class="centerr pt40 pb40">
			<div class="fz24 fwb texto_laranja"><?=$item->nome?></div>

			<div class="pt30 pb40">
				<?=txt($item)?>
				<div class="h10 clear"></div>
				<!-- Comentado por Diogo 21/06/2019 - para remover as redes sociais  <?=rede()?> -->
			</div>

			<? if($mais_fotos){ ?>
				<ul>
					<? foreach ($mais_fotos as $key => $value) { ?>
						<? $img->link = 1 ?>
						<li class="wr3 pb30 tac"><?=$img->img($value, 200, 200)?></li>
						<?=clear($key, 4)?>
					<? } ?>
					<div class="clear"></div>
				</ul>
			<? } ?>

		</div>


	</section>