
	<? if($_GET['pg'] != 'imprimir'){ ?>
	<footer>
		
		<div class="back_<?=LARANJA?>">
			<div class="centerr pt40 pb40">
				<div class="wr6 borda_newsletter">
                    <div class="pt5 pb10 texto_branco">
                        <p class="texto_laranja texto_negrito pb10">NEWSLETTER</p>
                        Cadastre-se para receber as novidades.
                    </div>
                    <form id="form_newsletter" action="" method="post" >
                        <input type="email" name="email" class="mb5 mr5 design w280 fll" placeholder="Email" required />
                        <button class="p11 m0 fundo_laranja botao_cadastrar_rodape">Cadastrar</button>
                        <div class="clear"></div>
                        <input type="reset" class="dni" />
                    </form>
                    <script>ajaxForm('form_newsletter', 'newsletter.php')</script>
                    <div class="pt10 pb10 texto_branco">
                        <p class="texto_laranja texto_negrito pb10">LOCALIZAÇÃO</p>
                        <div class="pb10">Anel Rodoviário Celso Mello Azevedo, 3713 - </div>

                        <div class="pb5">Bonsucesso - CEP 30622-213 - BH / MG</div>
                    </div>
				</div>

				<div class="wr6 tar">


                    <!---
                    <ul class="dib min-h100 pl20 pr20 tal vat db_700 bd0_700">
                        <li class="fwb ttu texto_laranja">Serviços</li>
                        <ul class="pt10">
                            <? foreach ($footer_servicos as $key => $value) { ?>
                                <li class="pb10"><a href="<?=url('servico', $value)?>" class="cor_fff"><?=$value->nome?></a></li>
                            <? } ?>
                        </ul>
                    </ul>
                    -->
					<div class="h20 dnn_700"></div>

                    <ul class="dib min-h100 pl20 pr20 tal vat db_700 bd0_700">
                        <li class="fwb ttu texto_laranja">Informações</li>
                        <ul class="pt10">
                            <li class="pb10"><a href="<?=url_txt(2)?>" class="cor_fff">Quem Somos</a></li>
                            <li class="pb10"><a href="<?=url_txt(1)?>" class="cor_fff">Termos de uso</a></li>
                            <? foreach ($paginas as $key => $value) { ?>
                                <li class="pb10"><a href="<?=url('textosp', $value)?>" class="cor_fff"><?=$value->nome?></a></li>
                            <? } ?>
                            <li class="pb10"><a href="<?=DIR?>/faq/" class="cor_fff">Perguntas Frequentes</a></li>
                            <li class="pb10"><a href="<?=DIR?>/fale/" class="cor_fff">Fale Conosco</a></li>
                        </ul>
                    </ul>

                    <div class="h20 dnn_700"></div>
					<ul class="dib min-h100 pl20 tal vat db_700">
						<li class="fwb ttu texto_laranja">Minha Conta</li>
						<ul class="pt10">
							<li class="pb10"><a href="<?=DIR?>/cadastro/" class="cor_fff">Cadastre-se</a></li>
							<li class="pb10"><a href="<?=DIR?>/login/" class="cor_fff">Login</a></li>
							<li class="pb10"><a onclick="boxs('esqueci_senha')" class="cor_fff">Esqueci minha senha</a></li>
						</ul>
					</ul>

                    <div class="h20 dnn_700"></div>
                    <!-- <ul class="dib min-h100 pl20 tal vat db_700">
                        <li class="fwb ttu texto_laranja">Redes Sociais</li>
                        <ul class="pt10">
                            <?=$info->facebook ? '<li class="dib p10"><a href="'.http($info->facebook).'" target="_blank" class="cor_fff hoverr-op8"><i class="icone_facebook"></i></a></li>' : ''?>
                        </ul>
                    </ul> -->
				</div>
				<div class="clear"></div>
			</div>
		</div>

       <div class="fundo_laranja">
           <div class="centerr pb40">
               <div class="pt10 texto_centralizado texto_branco">Uma empresa do grupo <i class="icone_brasilbrokers"></i></div>
               <div class="mt10 linha_branca_footer"></div>
               <div class="pt10 texto_centralizado texto_branco">2019 Copyright Brasil Brokers. Todos os direitos reservados</div>
               <div class="clear"></div>
            </div>
       </div>
	</footer>


	<? } ?>
