
	<section id="fale">

		<div class="centerr pt20 pb20">
			<div class="fz24 fwb texto_laranja pt20 pb20 borda_laranja_bottom"><?=lang('Fale Conosco')?></div>
		</div>


		<div class="">
			<div class="centerr pt20 pb20">
				<div class="wr6">

                    <b class="fz24"><?=lang('Tem alguma dúvida')?></b>

                    <div class="pt5 fz16">
                        <div class="pt15">
                            <?=lang('Entre em contato conosco através do formulário abaixo.')?>
                            <?=lang('Preencha os campos do formulário ao lado corretamente, nós responderemos em no máximo 24 horas.')?>
                        </div>
                    </div>

					<form id="form_fale" method="post" action="" enctype="multipart/form-data" >

						<input name="to" type="hidden" value="<?=$emails->email?>" />
						<input name="assunto" type="hidden" value="Contato" />

						<div class="p10">
							<div class="pt10 fwb"><?=lang('Nome')?>*</div>
                            <div class="pt10">
                                <input type="text" name="mail[campo][1]" class="design calc70" required />
                                <input type="hidden" name="mail[nome][1]" value="<?=lang('Nome')?>" />
                            </div>
						</div>
						<div class="wr6 p10">
							<div class="pt10 fwb"><?=lang('Email')?>*</div>
                            <div class="pt10">
                                <input type="email" name="mail[campo][3]" class="design calc60" required />
                                <input type="hidden" name="mail[nome][3]" value="<?=lang('Email')?>" />
                            </div>
						</div>

						<div class="wr6 p10">
							<div class="pt10 fwb"><?=lang('Telefone')?></div>
                            <div class="pt10">
                                <input type="tel" name="mail[campo][5]" class="design calc70"  />
                                <input type="hidden" name="mail[nome][5]" value="<?=lang('Telefone')?>" />
                            </div>
						</div>
						<div class="p10">
							<div class="pt10 fwb"><?=lang('Assunto')?></div>
                            <div class="pt10">
                                <input type="text" name="mail[campo][7]" class="design calc60" />
                                <input type="hidden" name="mail[nome][7]" value="<?=lang('Assunto')?>" />
                            </div>
						</div>
						<div class="clear"></div>

						<div class="p10">
							<div class="pt10 fwb"><?=lang('Mensagem')?></div>
                            <div class="pt10">
                                <textarea name="mail[campo][10]" class="design calc70 h150"></textarea>
                                <input type="hidden" name="mail[nome][10]" value="<?=lang('Mensagem')?>" />
                            </div>
						</div>

						<!--<div class="p10">
							<?=captcha()?>
						</div>-->

						<div class="pr10">
							<button class="p15 pl20 pr20 fz16 cor_fff fundo_laranja borda_arredondada bd0"><?=lang('Enviar')?></button>
						</div>

						<input type="reset" class="dni">
						<input type="hidden" name="log_gravacoes" value="1" />

					</form>
					<script>ajaxForm('form_fale', 'mail.php')</script>
				</div>

                <div class="wr6 mt10 p40 p0_700">

                    <div class="fundo_roxo cor_fff p20 tac borda_arredondada">
                        <div class="p5"><img src=".././web/img/icones/relogio-fale-conosco.png" alt="relógio" /></div>
                        <b class="fz16"><?=lang('Horário de Atendimento')?></b>
                        <div class="pt5 fz18"><?=$info->atendimento?></div>
                    </div>

                </div>
				<div class="clear"></div>
			</div>

		</div>


	</section>