
	<section id="login">

        <div class="h80"></div>
        <div class="mb10 fz24 texto_centralizado texto_laranja texto_negrito"><?=lang('Entre com a sua conta')?> </div>
        <div class="w500 w100p_500 m-a p20 cor_666 bd_ccc br10 back_fff">

            <? $url = $_GET['nome'] ?>
            <? $url .= $_GET['id']!='-' ? '/'.$_GET['id'] : ($_GET['categorias']!='-' ? '/-' : ''); ?>
            <? $url .= $_GET['categorias']!='-' ? '/'.$_GET['categorias'] : ''; ?>
            <? $url .= isset($_GET['ids']) ? '?ids='.$_GET['ids'] : ''; ?>

            <form id="form_login" method="post" action="">
                <input type="text" name="email" class="w100p design fz14" placeholder="<?=lang('Email ou Login')?>" required>
                <div class="h10 clear"></div>                   
                <input type="password" name="senha" class="w100p design fz14" placeholder="<?=lang('Senha')?>" required>
                <div class="clear mt20 mb20 linha_laranja"></div>

                <a onclick="boxs('esqueci_senha')" class="fll c_azul link texto_negrito"><?=lang('Esqueceu sua senha?')?></a>
                <a href="<?=DIR?>/cadastro/<?=$url?>" class="flr c_azul link texto_negrito"> <?=lang('Cadastre-se grátis')?> </a>
                <div class="clear"></div>

                <div class="tac pt15"><button class="w100p design p10 fz18 fwb ttu cor_fff fundo_roxo hover2 hoverr4 br5"><?=lang('Entrar')?></button></div>
                <div class="h20 clear"></div>

                <input type="hidden" name="direcionar" value="<?=$url?>" />
                <input type="hidden" name="fazer_login" value="1">
            </form>
            <script>ajaxForm('form_login', 'login.php')</script>
            <div class="clear"></div>
        </div>
        <div class="h80 clear"></div>

	</section>