
<style>



</style>

	<section id="lote" class="LL_box_<?=$item->id?>">

		<? if(isset($leiloes->id)){ ?>
			<div class="centerr pt40 pb40">

				<? include 'z_top_lote.phtml' ?>
				<div class="clear"></div>


				<h1 class="pt40 fz30 fwb cor_221E1F">Lote <?=$item->ordem?> - <span class="LL_nome"></span> <!--- <span class="LL_local"></span>--></h1>

				<div>
					<ul class="fll pt10">
						<li class="fll pr10 pb10 fz12 ttu texto_preto">
							<div class="dib p8 pl10 pr10 bd_ccc LL_natureza"></div>
						</li>
						<li class="fll pr10 pb10 fz12 ttu cor_fff">
							<div class="dib p8 pl10 pr10 cor_333 bd_ccc LL_tipos"></div>
						</li>
						<li class="fll pr10 pb10 fz12 ttu cor_fff">
							<div class="dib p8 pl10 pr10 cor_333 bd_ccc LL_praca_info"></div>
						</li>
						<li class="clear"></li>
					</ul>
					<? if(count($lotes) > 1){ ?>
						<?
							$value_left = '';
							$value_right = '';
							$vez = 0;
							foreach ($lotes as $key => $value) {
								if($item->id==$value->id){
									$vez++;
								} elseif(!$vez){
									$value_left = $value;
								} elseif($vez AND !$value_right){
									$value_right = $value;
								}
							}
						?>
						<ul class="flr pt8">
							<? if($value_left){ ?>
								<a href="<?=url('lote', $value_left)?>" class="dib p9 pb8 fz16 vam cor_fff back_ccc br2"><i class="fa fa-chevron-left"></i></a>
							<? } ?>
							<select class="dib max-w200 designx" onchange="location=options[selectedIndex].value">
								<? foreach ($lotes as $key => $value) { ?>
									<option value="<?=url('lote', $value)?>" <?=$item->id==$value->id ? 'selected' : ''?>>Leilão: <?=$leiloes->codigo?> - Lote: <?=(int)$value->ordem?></option>
								<? } ?>
							</select>
							<? if($value_right){ ?>
								<a href="<?=url('lote', $value_right)?>" class="dib p9 pb8 fz16 vam cor_fff back_ccc br2"><i class="fa fa-chevron-right"></i></a>
							<? } ?>
							<div class="clear"></div>
						</ul>
					<? } ?>
				</div>
				<div class="clear"></div>
				<hr class="bd0 bdb_E1E1E1">


				<div class="pt15 pb15 fz14 cor_<?=LARANJA?>">
					<div class="fll mr20"><div class="dib w15"><i class="fa fa-eye texto_laranja"></i></div></i> <span class="LL_count">--</span> <?=lang('visualizações')?></div>
					<a href="#box_info_leilao" onclick="box_leiloes_info(5, this)" class="fll pt2 cor_<?=LARANJA?> back0"><div class="dib w15"><i class="fa fa-gavel texto_laranja"></i></div> <span class="LL_count_lances">--</span> <?=lang('lance(s)')?></a>
					<!--<div class="fll pt2 pl30"><?=rede()?></div>-->
					<div class="clear"></div>
				</div>




				<div class="wr4 posr pl5 pr5">
					<div class="pb5 Plugin_CSS_galeriaa no_pagg">
						<?=Galeria_Produtos($item, 500, 500, 3, 1, 1)?>
					</div>
				</div>




				<div class="h15 dnn_700"></div>
				<div class="wr4 pl5 pr5 p0_700">

                    <div class="p30 pt28 pb28 borda_leiloes">
                        <div class="pt10 pb10 fz26 fwb cor_<?=LARANJA?>"><?=lang('Informações')?></div>
                        <div class="fz14 cor_666">
                            <ul class="">
                                <li class="pt16 pb16">
                                    <span class="dib fz15"><i class="icone_bandeira"></i><b><?=lang('Lote')?>:</b></span>
                                    <span class="LL_codigo"></span> / <?=(int)$item->ordem?>
                                </li>

                                <li class="pt16 pb16 LL_data_ini">
                                    <span class="dib fz15 mr10"><i class="icone_calendario pt5 pb5"></i><b><?=lang('Início')?>:</b></span>
                                    <span class="">
                                      <data class="dib"></data> <?=lang('às')?>
                                      <hora class="dib"></hora>
                                    </span>
                                </li>
                                <li class="pt16 pb16 LL_data_fim">
                                    <span class="dib fz15"><i class="icone_calendario pt5 pb5"></i><b><?=lang('Término')?>:</b></span>
                                    <span class="">
                                      <data class="dib"></data> <?=lang('às')?>
                                      <hora class="dib"></hora>
                                    </span>
                                </li>
                                <li class="pt16 pb16">
                                    <span class="dib fz15"><i class="icone_local pt5 pb5"></i><b><?=lang('Localidade')?>:</b></span>
                                    <span class="LL_local"></span>
                                </li>
                                <!--
                                <li class="pt5">
                                   	<span class="dib w6=50 fz11"><b><?=lang('Despesas')?>:</b></span>
									<span> R$
                                      <?

                                    $mysql->filtro = "WHERE id = '" . $item->id. "'";
                                    $lote_completo = $mysql->read_unico('lotes');

                                    echo $lote_completo->outras_despesas;
                                    ?>
                                    </span>

                                </li>
                                -->

                                <li class="pt16 pb16">
                                    <span class="dib fz15"><i class="icone_coins_solid pt5 pb5"></i><b><?=lang('Comissão do Leiloeiro')?>:</b></span>
                                    <span> 5% </span>
                                </li>

                                <li class="pt16 pb16 LL_lance_ini">
                                    <div class="fz14 fwb"><?=lang('Lance Inicial')?>:</div>
                                    <b class="fz25 cor_<?=LARANJA?>"></b>
                                </li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>

				</div>




				<div class="wr4 pl5 pr5 aovivo">
                    <div class="p5 pl15 pr15 fz14 ttu ts1 cor_fff mb5 LL_situacao">
                        <p class="tac"></p>
                        <div class="clear"></div>
                    </div>
					<? $aovivo = cod('asc->html', stripcslashes($leiloes->aovivo)); ?>
					<?
						if(isset($_GET['sincronizar'])){
							$entre1 = entre('src=&#34;', '&#34;', $leiloes->aovivo);
							$integ = preg_match('(&#63;)', $entre1) ? '&' : '?';

							$entre = entre('src="', '"', $aovivo);
							$aovivo = str_replace($entre, $entre.$integ.'autoplay=1', $aovivo);
						} 
					?>
					<? if($aovivo AND $leiloes->promocao){ ?>
						<div class="p20 mb15 o-h back_F6F6F6">
							<div class="posr fz26 fwb cor_<?=LARANJA?>">
								<?=lang('Ao Vivo')?>
								<a class="posa dn r10 b5 fz12 cor_00f link LL_sincronizar"><?=lang('Sincronizar')?></a>
							</div>
							<div class="pt10"><?=$aovivo?></div>
						</div>
						<? if(isset($_GET['sincronizar'])){ ?>
							<script>
								setTimeout(function(){
									$("html,body").animate( {scrollTop: $(".LL_nome").offset().top}, "fast" );
								}, 500);
	 						</script>
						<? } ?>
					<? } ?>
					<div class="p5 pl0 pr0 mb5 cor_fff fundo_roxo LL_cronometro">
						<div class="tac ttu LL_cronometro_info"></div>
						<div class="pt5 fz18 fwb tac LL_cronometro_tempo">
							<div class="dib vat LL_dias">
								<span>--</span> :
								<div class="pr18 fz10 fwb ttu tac"><?=lang('dias')?></div>
							</div>
							<div class="dib vat LL_hora">
								<span>--</span> :
								<div class="pr18 fz10 fwb ttu tac"><?=lang('horas')?></div>
							</div>
							<div class="dib vat LL_min">
								<span>--</span> :
								<div class="pr18 fz10 fwb ttu tac"><?=lang('min')?></div>
							</div>
							<div class="dib vat LL_seg">
								<span>--</span>
								<div class="fz10 fwb ttu tac"><?=lang('seg')?></div>
							</div>
						</div>
					</div>
					<div class="p5 pl0 pr0 tac borda_roxa" style="min-height: 80px;">
						<div class="LL_lance_atual">
							<span class="db fwb ttu cor_666"></span>
							<b class="pt2 fz18 vas tac cor_<?=LARANJA?>"></b>
						</div>
						<div class="">
							<div class="fz10 fwb cor_666 LL_lances_data"></div>
							<b class="pt2 fz12 vas tac cor_666 LL_lances_cadastro"></b>
						</div>
						<div class="clear"></div>
					</div>

                    <div class="p20 pt5 pb8 mt5 back_F6F6F6 LL_dar_lance">
                        <div class="pb8 fz16 fwb cor_<?=LARANJA?>"><?=lang('Dê seu lance')?></div>
                        <? if($item->incremento > 0 AND $item->situacao!=20){ ?>
                            <div class="dn_700">
                                <ul>
                                    <? for ($i=1; $i < 9; $i++) { ?>
                                        <li class="wr6 wr12_700 mb5 p0_700 pr10">
                                            <a onclick="dar_lance(<?=$item->id?>, this)" class="db borda_roxa hoverr-op6" >
                                                <i class="fa fa-plus posa w30 h20 pt5 pb5 mt3 mb3 tac borda_roxa_direita"></i>
                                                <div class="p6 pl10 pr10 ml30">
                                                    <?=preco($item->incremento*$i, 1)?>
                                                    <input type="hidden" name="lance_mais" value="<?=$item->incremento*$i?>">
                                                </div>
                                            </a>
                                        </li>
                                    <? } ?>
                                    <div class="clear"></div>
                                </ul>
                                <div class="pt4 pb2 fz14 texto_roxo fwb"><?=lang('Para outros valores')?>:</div>
                            </div>
                        <? } ?>
                        <form id="form_lance" method="post" action="javascript:void(0)" onsubmit="dar_lance(<?=$item->id?>, this)" enctype="multipart/form-data" >
                            <div class=""><input type="search" name="lance" class="p8 bd0 preco1 w100p fz14" placeholder="Informe o valor (Ex. R$ 15.000,00)" required></div>
                            <div class="pt10 tac"><button class="w100p p15 pt5 pb5 fz16 cor_fff bd0 fundo_laranja hoverr-op6"><?=lang('Confirmar lance')?></button></div>
                        </form>
                    </div>

                    <? if(!count($lotes_habilitacoes_sucata) AND $item->sucata){ ?>
                        <div class="pt15 tac">
                            <a onclick="habilitar_lote_sucata('<?=$item->id?>')" class="botao dib p10 pl30 pr30 fz14 fwb ttu cor_fff back_00C200 LL_habilitar_lote_sucata"><?=lang('HABILITAR-SE PARA LOTE DE SUCATA')?></a>
                        </div>
                    <? } ?>

				</div>
				<div class="clear"></div>



				<div class="wr12 p20 borda_bottom">
                    <h2 class="texto_roxo"><?=lang('Descrição')?></h2>
                    <?=txt($item)?>
                </div>


                <? if($item->foto10){ ?>

                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=lang('Edital')?></h2>

                            <div class="wr8"><?=$item->foto10?></div>
                            <div class="wr3 tar texto_laranja texto_negrito">
                                <a href="<?=DIR?>/web/fotos/<?=$item->foto10?>" target="_blank" class="box_ db p10" style="overflow: hidden;"><i class="icone_download_solid"></i><span class="texto_laranja"><?=lang('Baixar arquivo')?></span></a>
                            </div>

                    </div>

                <? } ?>

                <? if($item->anexo1 AND $item->foto1){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->anexo1?></h2>
                        <a href="<?=DIR?>/web/fotos/<?=$item->foto1?>" target="_blank" class="box_ db p10">
                            <div class="wr8"><?=$item->foto1?></div>
                            <div class="wr3 tar texto_laranja texto_negrito"><?=$item->anexo1?></div>
                        </a>
                    </div>
                <? } ?>

                <? if($item->anexo2 AND $item->foto2){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->anexo2?></h2>
                        <a href="<?=DIR?>/web/fotos/<?=$item->foto2?>" target="_blank" class="box_ db p10">
                            <div class="wr8"><?=$item->foto2?></div>
                            <div class="wr3 tar texto_laranja texto_negrito"><?=$item->anexo2?></div>
                        </a>
                    </div>
                <? } ?>

                <? if($item->anexo3 AND $item->foto3){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->anexo3?></h2>
                         <a href="<?=DIR?>/web/fotos/<?=$item->foto3?>" target="_blank" class="box_ db p10">
                             <div class="wr8"><?=$item->foto3?></div>
                             <div class="wr3 tar texto_laranja texto_negrito"><?=$item->anexo3?></div>
                         </a>
                    </div>
                <? } ?>

                <? if($item->anexo4 AND $item->foto4){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->anexo4?></h2>
                        <a href="<?=DIR?>/web/fotos/<?=$item->foto4?>" target="_blank" class="box_ db p10">
                            <div class="wr8"><?=$item->foto4?></div>
                            <div class="wr3 tar texto_laranja texto_negrito"><?=$item->anexo4?></div>
                        </a>
                    </div>
                <? } ?>


                <? if($item->anexo5 AND $item->foto5){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->anexo5?></h2>
                        <a href="<?=DIR?>/web/fotos/<?=$item->foto5?>" target="_blank" class="box_ db p10">
                            <div class="wr8">
                                <?=$item->foto5?>
                            </div>
                            <div class="wr3 tar texto_laranja texto_negrito">
                                <?=$item->anexo5?>
                            </div>
                        </a>
                    </div>
                <? } ?>

                <? if($item->txt_extra_01){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->txt_extra_01?></h2>
                        <?=txt($item, 1)?>
                    </div>
                <? } ?>

                <? if($item->txt_extra_02){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->txt_extra_02?></h2>
                        <?=txt($item, 2)?>
                    </div>
                <? } ?>

                <? if($item->txt_extra_03){ ?>
                    <div class="wr12 p20 borda_bottom">
                        <h2 class="texto_roxo"><?=$item->txt_extra_03?></h2>
                        <?=txt($item, 3)?>
                    </div>
                <? } ?>

                <? $mapa = cod('asc->html', stripcslashes($item->google_maps)); ?>
                <? if($mapa){ ?>
                    <div class="wr12 p20">
                        <h2 class="texto_roxo"><?=lang('Mapa')?></h2>
                        <?=mapaa($mapa, '100%', 500)?>
                    </div>
                <? } ?>

                <div class="wr12 p20 borda_bottom">
                    <h2 class="texto_roxo">Detalhes</h2>
                    <p class="pt5 pb5">
                        <div class="dib p8"><span class="fas fa-vector-square" title="Área" style="font-size: 25px;font-weight: bold;"></span> Tamanho do imóvel: <?=$item->area_privativa?> m²</div>
                        <div class="dib p8"><span class="fas fa-car" title="Vagas" style="font-size: 25px;font-weight: bold;"></span> Vagas privativas: <?=$item->vagas?></div>
                        <div class="dib p8"><span class="fas fa-bed" title="Quartos" style="font-size: 25px;font-weight: bold;"></span> Número de quartos: <?=$item->quartos?></div>
                        <div class="dib p8"><span class="fas fa-chess-queen" title="Suítes" style="font-size: 25px;font-weight: bold;"></span> Número de suítes: <?=$item->suites?></div>
                        <div class="dib p8"><span class="fas fa-bath" title="Banheiros" style="font-size: 25px;font-weight: bold;"></span> Número de banheiros: <?=$item->banheiros?></div>
                    </p>
                </div>

                <div class="wr12 p20 borda_bottom">
                    <h2 class="texto_roxo">Infraestrutura</h2>
                    <style>
                        .infra {
                            padding: 10px;
                            display: inline-block;
                        }
                    </style>
                    <p>
                       <?php echo empty($item->academia)? '':('<span class="infra">Academia</span>'); ?>
                       <?php echo empty($item->bicicletario)? '':('<span class="infra">Bicicletário</span>'); ?>
                       <?php echo empty($item->brinquedoteca)? '':('<span class="infra">Brinquedoteca</span>'); ?>
                       <?php echo empty($item->campo_de_futebol)? '':('<span class="infra">Campo de futebol</span>'); ?>
                       <?php echo empty($item->churrasqueira)? '':('<span class="infra">Churrasqueira</span>'); ?>
                       <?php echo empty($item->cinema)? '':('<span class="infra">Cinema</span>'); ?>
                       <?php echo empty($item->pet_care)? '':('<span class="infra">Pet care</span>'); ?>
                       <?php echo empty($item->piscina)? '':('<span class="infra">Piscina</span>'); ?>
                       <?php echo empty($item->piscina_infantil)? '':('<span class="infra">Piscina infantil</span>'); ?>
                       <?php echo empty($item->pista_de_skate)? '':('<span class="infra">Pista de skate</span>'); ?>
                       <?php echo empty($item->playground)? '':('<span class="infra">Playground</span>'); ?>
                       <?php echo empty($item->quadra_de_futsal)? '':('<span class="infra">Quadra de futsal</span>'); ?>
                       <?php echo empty($item->quadra_de_tenis)? '':('<span class="infra">Quadra de tênis</span>'); ?>
                       <?php echo empty($item->restaurante)? '':('<span class="infra">Restaurante</span>'); ?>
                       <?php echo empty($item->sala_de_massagem)? '':('<span class="infra">Sala de massagem</span>'); ?>
                       <?php echo empty($item->salao_de_beleza)? '':('<span class="infra">Salão de beleza</span>'); ?>
                       <?php echo empty($item->salao_de_festas)? '':('<span class="infra">Salão de festas</span>'); ?>
                       <?php echo empty($item->salao_de_festas_infantil)? '':('<span class="infra">Salão de festas infantil</span>'); ?>
                       <?php echo empty($item->salao_de_jogos)? '':('<span class="infra">Salão de jogos</span>'); ?>
                       <?php echo empty($item->sauna)? '':('<span class="infra">Sauna</span>'); ?>
                       <?php echo empty($item->spa)? '':('<span class="infra">Spa</span>'); ?>
                       <?php echo empty($item->vagas_de_visitantes)? '':('<span class="infra">Vagas de visitantes</span>'); ?>


                    </p>
                </div>

                <? if($item->situacao!=20){ ?>


                    <div class="wr12 p20" style="overflow-x: auto;">
                        <h2  class="texto_roxo"><?=lang('Histórico de lances')?></h2>
                        <table class="w100p">
                            <thead>
                            <tr class="bdb_F7F7F7">
                                <td class="p10 tac"><?=lang('TIPO')?></td>
                                <td class="p10 tac"><?=lang('USÚARIO / PLAQUETA')?></td>
                                <td class="p10 tac"><?=lang('DATA')?></td>
                                <td class="p10 tac"><?=lang('HORA')?></td>
                                <td class="p10 tac"><?=lang('VALOR')?></td>
                            </tr>
                            </thead>
                            <tbody class="LL_historico"></tbody>
                        </table>
                    </div>

                <? } ?>

				<script>box_leiloes_info_ini()</script>

			</div>

			<script>
				atualizar_leiloes('', '', '<?=$item->id?>');
				cronometro();
				historico('<?=$item->id?>');
			</script>

		<? } else { ?>
			<div class="p40 fz14 tac"><?=lang('Nenhum Lote Encontrado')?>...</div>
		<? } ?>

	</section>

<script>
    $(document).ready(function () {
        //Ativando toolips
        $(document).tooltip();
    });
</script>